### ISSUE TITLE
Add "check" / prevent illegal moves

### ISSUE THREAD

**Issue by jerome3o** [williamsnell/hexchess#1]
I was playing with a friend (session id: `b6a49219-ff84-45b0-af0f-77cc8e4cfae5`) and during the game he made an illegal move, where he moved his king into a checked position. This wasn't too bad because I just did a dummy move to let him uncheck himself, but this wouldn't fly in an official hexchess tournament. Please, if you want this to be taken seriously add check functionality.

**Comment by CallumFergs** [comment]
Can vouch, I was the friend in this game. When this occurred I was mentally thrown off and this impacted my ability to concentrate on the rest of the game.

**Comment by williamsnell** [comment]
Fixed as of https://github.com/williamsnell/hexchess/commit/7ef6f7519d363890924da9224bf71297674a7cba
