### ISSUE TITLE
Game disconnected

### ISSUE THREAD

**Issue by vahfanforever** [williamsnell/hexchess#2]
I was in the middle of a very intense match when the game suddenly disconnected

**Comment by jerome3o** [comment]
Same here ^

**Comment by jerome3o** [comment]
It could be worth adding some re-connect logic. Do you think this would be a good first issue to solve for @vahfanforever ?

**Comment by williamsnell** [comment]
Thanks for raising this issue! It was definitely sucky design :)

As of [this commit](https://github.com/williamsnell/hexchess/commit/33dacaa3ba4795fd71c67f4f116afd77755f16f7) games will restore so long as the tab they were created on can be reloaded (e.g. if the tab is accidentally closed, ctrl+shift+T should resume it)
